<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.3" release="Tue Feb 21 16:20:52 2017 -0800">
<training_set datafile="/Users/Javaid/Downloads/chexmix-master/Fis_Heatshock_REP_chexmix/intermediate-results/seq11538737408189954444.fa" length="112">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="Seq1" length="61" weight="1.000000" />
<sequence id="sequence_1" name="Seq2" length="61" weight="1.000000" />
<sequence id="sequence_2" name="Seq3" length="61" weight="1.000000" />
<sequence id="sequence_3" name="Seq4" length="61" weight="1.000000" />
<sequence id="sequence_4" name="Seq5" length="61" weight="1.000000" />
<sequence id="sequence_5" name="Seq6" length="61" weight="1.000000" />
<sequence id="sequence_6" name="Seq7" length="61" weight="1.000000" />
<sequence id="sequence_7" name="Seq8" length="61" weight="1.000000" />
<sequence id="sequence_8" name="Seq9" length="61" weight="1.000000" />
<sequence id="sequence_9" name="Seq10" length="61" weight="1.000000" />
<sequence id="sequence_10" name="Seq11" length="61" weight="1.000000" />
<sequence id="sequence_11" name="Seq12" length="61" weight="1.000000" />
<sequence id="sequence_12" name="Seq13" length="61" weight="1.000000" />
<sequence id="sequence_13" name="Seq14" length="61" weight="1.000000" />
<sequence id="sequence_14" name="Seq15" length="61" weight="1.000000" />
<sequence id="sequence_15" name="Seq16" length="61" weight="1.000000" />
<sequence id="sequence_16" name="Seq17" length="61" weight="1.000000" />
<sequence id="sequence_17" name="Seq18" length="61" weight="1.000000" />
<sequence id="sequence_18" name="Seq19" length="61" weight="1.000000" />
<sequence id="sequence_19" name="Seq20" length="61" weight="1.000000" />
<sequence id="sequence_20" name="Seq21" length="61" weight="1.000000" />
<sequence id="sequence_21" name="Seq22" length="61" weight="1.000000" />
<sequence id="sequence_22" name="Seq23" length="61" weight="1.000000" />
<sequence id="sequence_23" name="Seq24" length="61" weight="1.000000" />
<sequence id="sequence_24" name="Seq25" length="61" weight="1.000000" />
<sequence id="sequence_25" name="Seq26" length="61" weight="1.000000" />
<sequence id="sequence_26" name="Seq27" length="61" weight="1.000000" />
<sequence id="sequence_27" name="Seq28" length="61" weight="1.000000" />
<sequence id="sequence_28" name="Seq29" length="61" weight="1.000000" />
<sequence id="sequence_29" name="Seq30" length="61" weight="1.000000" />
<sequence id="sequence_30" name="Seq31" length="61" weight="1.000000" />
<sequence id="sequence_31" name="Seq32" length="61" weight="1.000000" />
<sequence id="sequence_32" name="Seq33" length="61" weight="1.000000" />
<sequence id="sequence_33" name="Seq34" length="61" weight="1.000000" />
<sequence id="sequence_34" name="Seq35" length="61" weight="1.000000" />
<sequence id="sequence_35" name="Seq36" length="61" weight="1.000000" />
<sequence id="sequence_36" name="Seq37" length="61" weight="1.000000" />
<sequence id="sequence_37" name="Seq38" length="61" weight="1.000000" />
<sequence id="sequence_38" name="Seq39" length="61" weight="1.000000" />
<sequence id="sequence_39" name="Seq40" length="61" weight="1.000000" />
<sequence id="sequence_40" name="Seq41" length="61" weight="1.000000" />
<sequence id="sequence_41" name="Seq42" length="61" weight="1.000000" />
<sequence id="sequence_42" name="Seq43" length="61" weight="1.000000" />
<sequence id="sequence_43" name="Seq44" length="61" weight="1.000000" />
<sequence id="sequence_44" name="Seq45" length="61" weight="1.000000" />
<sequence id="sequence_45" name="Seq46" length="61" weight="1.000000" />
<sequence id="sequence_46" name="Seq47" length="61" weight="1.000000" />
<sequence id="sequence_47" name="Seq48" length="61" weight="1.000000" />
<sequence id="sequence_48" name="Seq49" length="61" weight="1.000000" />
<sequence id="sequence_49" name="Seq50" length="61" weight="1.000000" />
<sequence id="sequence_50" name="Seq51" length="61" weight="1.000000" />
<sequence id="sequence_51" name="Seq52" length="61" weight="1.000000" />
<sequence id="sequence_52" name="Seq53" length="61" weight="1.000000" />
<sequence id="sequence_53" name="Seq54" length="61" weight="1.000000" />
<sequence id="sequence_54" name="Seq55" length="61" weight="1.000000" />
<sequence id="sequence_55" name="Seq56" length="61" weight="1.000000" />
<sequence id="sequence_56" name="Seq57" length="61" weight="1.000000" />
<sequence id="sequence_57" name="Seq58" length="61" weight="1.000000" />
<sequence id="sequence_58" name="Seq59" length="61" weight="1.000000" />
<sequence id="sequence_59" name="Seq60" length="61" weight="1.000000" />
<sequence id="sequence_60" name="Seq61" length="61" weight="1.000000" />
<sequence id="sequence_61" name="Seq62" length="61" weight="1.000000" />
<sequence id="sequence_62" name="Seq63" length="61" weight="1.000000" />
<sequence id="sequence_63" name="Seq64" length="61" weight="1.000000" />
<sequence id="sequence_64" name="Seq65" length="61" weight="1.000000" />
<sequence id="sequence_65" name="Seq66" length="61" weight="1.000000" />
<sequence id="sequence_66" name="Seq67" length="61" weight="1.000000" />
<sequence id="sequence_67" name="Seq68" length="61" weight="1.000000" />
<sequence id="sequence_68" name="Seq69" length="61" weight="1.000000" />
<sequence id="sequence_69" name="Seq70" length="61" weight="1.000000" />
<sequence id="sequence_70" name="Seq71" length="61" weight="1.000000" />
<sequence id="sequence_71" name="Seq72" length="61" weight="1.000000" />
<sequence id="sequence_72" name="Seq73" length="61" weight="1.000000" />
<sequence id="sequence_73" name="Seq74" length="61" weight="1.000000" />
<sequence id="sequence_74" name="Seq75" length="61" weight="1.000000" />
<sequence id="sequence_75" name="Seq76" length="61" weight="1.000000" />
<sequence id="sequence_76" name="Seq77" length="61" weight="1.000000" />
<sequence id="sequence_77" name="Seq78" length="61" weight="1.000000" />
<sequence id="sequence_78" name="Seq79" length="61" weight="1.000000" />
<sequence id="sequence_79" name="Seq80" length="61" weight="1.000000" />
<sequence id="sequence_80" name="Seq81" length="61" weight="1.000000" />
<sequence id="sequence_81" name="Seq82" length="61" weight="1.000000" />
<sequence id="sequence_82" name="Seq83" length="61" weight="1.000000" />
<sequence id="sequence_83" name="Seq84" length="61" weight="1.000000" />
<sequence id="sequence_84" name="Seq85" length="61" weight="1.000000" />
<sequence id="sequence_85" name="Seq86" length="61" weight="1.000000" />
<sequence id="sequence_86" name="Seq87" length="61" weight="1.000000" />
<sequence id="sequence_87" name="Seq88" length="61" weight="1.000000" />
<sequence id="sequence_88" name="Seq89" length="61" weight="1.000000" />
<sequence id="sequence_89" name="Seq90" length="61" weight="1.000000" />
<sequence id="sequence_90" name="Seq91" length="61" weight="1.000000" />
<sequence id="sequence_91" name="Seq92" length="61" weight="1.000000" />
<sequence id="sequence_92" name="Seq93" length="61" weight="1.000000" />
<sequence id="sequence_93" name="Seq94" length="61" weight="1.000000" />
<sequence id="sequence_94" name="Seq95" length="61" weight="1.000000" />
<sequence id="sequence_95" name="Seq96" length="61" weight="1.000000" />
<sequence id="sequence_96" name="Seq97" length="61" weight="1.000000" />
<sequence id="sequence_97" name="Seq98" length="61" weight="1.000000" />
<sequence id="sequence_98" name="Seq99" length="61" weight="1.000000" />
<sequence id="sequence_99" name="Seq100" length="61" weight="1.000000" />
<sequence id="sequence_100" name="Seq101" length="61" weight="1.000000" />
<sequence id="sequence_101" name="Seq102" length="61" weight="1.000000" />
<sequence id="sequence_102" name="Seq103" length="61" weight="1.000000" />
<sequence id="sequence_103" name="Seq104" length="61" weight="1.000000" />
<sequence id="sequence_104" name="Seq105" length="61" weight="1.000000" />
<sequence id="sequence_105" name="Seq106" length="61" weight="1.000000" />
<sequence id="sequence_106" name="Seq107" length="61" weight="1.000000" />
<sequence id="sequence_107" name="Seq108" length="61" weight="1.000000" />
<sequence id="sequence_108" name="Seq109" length="61" weight="1.000000" />
<sequence id="sequence_109" name="Seq110" length="61" weight="1.000000" />
<sequence id="sequence_110" name="Seq111" length="61" weight="1.000000" />
<sequence id="sequence_111" name="Seq112" length="61" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.265</value>
<value letter_id="C">0.235</value>
<value letter_id="G">0.235</value>
<value letter_id="T">0.265</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme /Users/Javaid/Downloads/chexmix-master/Fis_Heatshock_REP_chexmix/intermediate-results/seq11538737408189954444.fa -dna -mod zoops -revcomp -nostatus -nmotifs 3 -minw 8 -maxw 21 -o /Users/Javaid/Downloads/chexmix-master/Fis_Heatshock_REP_chexmix/intermediate-results/meme_motif_SAMPLE_t3_s0_c1 </command_line>
<host>JAVAIDs-Air</host>
<type>zoops</type>
<nmotifs>3</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>8</min_width>
<max_width>21</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>112</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>112</num_sequences>
<num_positions>6832</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (3) found.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="A">0.265</value>
<value letter_id="C">0.235</value>
<value letter_id="G">0.235</value>
<value letter_id="T">0.265</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="15" sites="34" ic="13.9" re="13.6" llr="322" e_value="3.9e-012" bayes_threshold="8.06378" elapsed_time="2.619239">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">-141</value>
<value letter_id="G">165</value>
<value letter_id="T">-59</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">91</value>
<value letter_id="C">-68</value>
<value letter_id="G">-68</value>
<value letter_id="T">-36</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-117</value>
<value letter_id="C">139</value>
<value letter_id="G">-1173</value>
<value letter_id="T">0</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">178</value>
<value letter_id="C">-1173</value>
<value letter_id="G">-141</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">129</value>
<value letter_id="C">-100</value>
<value letter_id="G">-19</value>
<value letter_id="T">-317</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">191</value>
<value letter_id="C">-1173</value>
<value letter_id="G">-1173</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">122</value>
<value letter_id="C">-19</value>
<value letter_id="G">-41</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">108</value>
<value letter_id="C">-68</value>
<value letter_id="G">-100</value>
<value letter_id="T">-59</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-36</value>
<value letter_id="C">-200</value>
<value letter_id="G">46</value>
<value letter_id="T">63</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">-200</value>
<value letter_id="G">-1173</value>
<value letter_id="T">183</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">53</value>
<value letter_id="C">-1173</value>
<value letter_id="G">139</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">178</value>
<value letter_id="C">-1173</value>
<value letter_id="G">-141</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-36</value>
<value letter_id="C">59</value>
<value letter_id="G">-19</value>
<value letter_id="T">-17</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1173</value>
<value letter_id="C">205</value>
<value letter_id="G">-299</value>
<value letter_id="T">-1173</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">100</value>
<value letter_id="C">-1173</value>
<value letter_id="G">17</value>
<value letter_id="T">-36</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.088235</value>
<value letter_id="G">0.735294</value>
<value letter_id="T">0.176471</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.500000</value>
<value letter_id="C">0.147059</value>
<value letter_id="G">0.147059</value>
<value letter_id="T">0.205882</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.117647</value>
<value letter_id="C">0.617647</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.264706</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.911765</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.088235</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.647059</value>
<value letter_id="C">0.117647</value>
<value letter_id="G">0.205882</value>
<value letter_id="T">0.029412</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.617647</value>
<value letter_id="C">0.205882</value>
<value letter_id="G">0.176471</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.558824</value>
<value letter_id="C">0.147059</value>
<value letter_id="G">0.117647</value>
<value letter_id="T">0.176471</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.205882</value>
<value letter_id="C">0.058824</value>
<value letter_id="G">0.323529</value>
<value letter_id="T">0.411765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.058824</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.941176</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.382353</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.617647</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.911765</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.088235</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.205882</value>
<value letter_id="C">0.352941</value>
<value letter_id="G">0.205882</value>
<value letter_id="T">0.235294</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.970588</value>
<value letter_id="G">0.029412</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.529412</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.264706</value>
<value letter_id="T">0.205882</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
G[AT][CT]A[AG]A[AC]A[TGA]T[GA]A[CTAG]C[AGT]
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_40" position="24" strand="plus" pvalue="1.69e-07" >
<left_flank>TATCGAATAC</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>CATAACCTTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_49" position="29" strand="minus" pvalue="2.84e-07" >
<left_flank>ACGCTGGACA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>GGCTATTTTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_45" position="26" strand="plus" pvalue="5.17e-07" >
<left_flank>AGAAGTCAAA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>CCCTATAAAC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_83" position="6" strand="plus" pvalue="6.08e-07" >
<left_flank>TAATAT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>GGAAAAAGTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_22" position="33" strand="plus" pvalue="6.08e-07" >
<left_flank>GGTTAATTAT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GAATGAATAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_1" position="12" strand="minus" pvalue="1.79e-06" >
<left_flank>AGATTGCCTT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>ATATATTTGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_65" position="18" strand="plus" pvalue="2.08e-06" >
<left_flank>CTGGAAGCGA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GCGGATAGCG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="23" strand="plus" pvalue="3.17e-06" >
<left_flank>TGCAATTCAG</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>ACCCCTCAAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_63" position="21" strand="plus" pvalue="4.08e-06" >
<left_flank>CTGTGATGTT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>TAATAAACAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_25" position="22" strand="plus" pvalue="4.64e-06" >
<left_flank>TGCCCAAGAT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>GTGCGCGACG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_57" position="18" strand="plus" pvalue="5.31e-06" >
<left_flank>CACCGCGCCT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>CGTTTGTTCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_8" position="22" strand="minus" pvalue="6.69e-06" >
<left_flank>CCCAAGATTA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ACCGCCTCTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_73" position="21" strand="minus" pvalue="7.52e-06" >
<left_flank>TTCTGGAAGC</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>